/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'AD9854' 
 * Target:  'STM32_CharLCD' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f10x.h"

/* Keil::Device:StdPeriph Drivers:DAC@3.6.0 */
#define RTE_DEVICE_STDPERIPH_DAC


#endif /* RTE_COMPONENTS_H */
